#include "SceneElt.hpp"



SceneElt::SceneElt() {}
SceneElt::~SceneElt() {}


//glouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglou
//glouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglou
//glouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglou
//glouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglou
//glouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglou
//glouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglou
//glouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglou
//glouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglou
//glouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglou
//glouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglou
//glouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglou
//glouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglouglou
//BEEEEUUUUUUUUUUAARRRRRRRRRRKKKKHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH!!!!!
